name: Deploy Infrastructure

on:
  push:
    branches:
      - main
# on:
#   workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep to Azure
        run: |
          az deployment group create --resource-group az400preparation --template-file main.bicep
